name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  file_picker: ^13.1.0
  flutter:
    sdk: flutter
  shader_fun:
    path: ../
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hooks: ^2.2.0

dependency_overrides:
  scene:
    path: ../../../tmp/flutter_scene/packages/scene

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/2d_texture/
    - flutter_scene_generated/
    - shaders/
