name: shader_fun
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.13.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gpu:
    sdk: flutter
  flutter_recorder: ^2.0.3
  flutter_soloud: ^5.0.2
  listen: ^1.0.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
